### ISSUE TITLE
Packer can't start ansible-playbook

### ISSUE THREAD

**Issue by benmoss** [ptylenda/kubernetes-for-windows#10]
Hey @ptylenda, @pablodav 

Trying to get this running, but struggling with creating the packer images. I launch ` .\packer-ansible-windows.ps1 build --only=hyperv-iso .\kubernetes-node-windows1803-march2018.json` from Powershell and packer successfully starts, but it fails to launch ansible-playbook.

```
2018/07/06 12:02:07 ui error: 1 error(s) occurred:

* Error running "ansible-playbook --version": exit status 1
2018/07/06 12:02:07 [INFO] (telemetry) Finalizing.
1 error(s) occurred:

* Error running "ansible-playbook --version": exit status 1
```

I think it might be because these are `cmd` wrappers, and Packer is trying to launch them using Go's os/exec package, rather than through a shell. I dealt with this before, Windows is happy to run `cmd` files as if they are extension-less binaries, but Go won't see them. Still, curious if you got this working somehow before.

If I run `ansible-playbook --version` from PS with that aliases dir on my path, it works just fine.

**Comment by ptylenda** [comment]
Well that is pretty odd, as in my case there were no problems when using Win10 + WSL and aliases. Have you tried adding aliases directory directly to PATH variable in system environment? (instead of relying at the .ps1 script to do so for every run)

BTW which Win 10 build number do you have exactly?

**Comment by pablodav** [comment]
I don't use packet in my tests, just some VMs that I use with snapshots or clones.

**Comment by benmoss** [comment]
Yeah, the `cmd` wrappers run fine from a Powershell with that directory on the PATH, but not when run from Packer. This is Windows 10.0.17134.0
