### ISSUE TITLE
vxlan support

### ISSUE THREAD

**Issue by benmoss** [ptylenda/kubernetes-for-windows#12]
Hey @ptylenda,

I see in the README you say that vxlan support is possible with this playbook, but I'm not entirely clear what is meant by "requires changes in network deployment file and installation of CNI plugins on Windows". I've seen https://github.com/Microsoft/SDN/tree/master/Kubernetes/flannel/overlay and have been trying to get it to work without much luck, so hoping you might have some clues.

Right now I can't seem to get inbound ip masquerading to work, packets from in the container go out but return packets aren't being routed back in as far as I can tell.

Ben

**Comment by benmoss** [comment]
Nevermind! I still can't get `ping 8.8.8.8` to work for some reason, but I can get regular curl requests to work to both the internet and other (Windows) pods.

**Comment by daschott** [comment]
@benmoss yes, for external connectivity please use TCP/UDP protocol. ICMP isn't supported today!
