### ISSUE TITLE
install_docker_msft in files No match was found for the specified search criteria and package name 'Docker'. 

### ISSUE THREAD

**Issue by saber13812002** [ptylenda/kubernetes-for-windows#14]
https://github.com/pablodav/kubernetes-for-windows/blob/feature/kubespray_k8win1803/ansible/roles/windows/docker/files/install_docker_msft.ps1

PS C:\Users\farm.admin\Documents> Install-Package Docker -ProviderName DockerMsftProvider -Confirm -RequiredVersion $Req
uiredVersion -Verbose -ForceBootstrap
VERBOSE: Using the provider 'DockerMsftProvider' for searching packages.
VERBOSE: Download size: 0.02MB
VERBOSE: Free space on the drive: 81328.66MB
VERBOSE: Downloading https://dockermsft.blob.core.windows.net/dockercontainer/DockerMsftIndex.json to
C:\Users\FARM~1.ADM\AppData\Local\Temp\DockerMsftProvider\DockerDefault_DockerSearchIndex.json
VERBOSE: About to download
VERBOSE: Finished downloading
VERBOSE: Downloaded in 0 hours, 0 minutes, 1 seconds.
Install-Package : No match was found for the specified search criteria and package name 'Docker'. Try
Get-PackageSource to see all available registered package sources.
At line:1 char:1

```
Install-Package Docker -ProviderName DockerMsftProvider -Confirm -Req ...
  + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Ex
 ception
  + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

```

**Comment by ptylenda** [comment]
Please check if `win_docker_version` variable that you are supplying in the vars file exists in the provider index (https://dockermsft.blob.core.windows.net/dockercontainer/DockerMsftIndex.json). And also try running manually the command
```
Install-Package Docker -ProviderName DockerMsftProvider -Confirm -RequiredVersion 18.03.1-ee-2 -Verbose
```

If the PackageManagement PowerShell module works correctly for a given version, then the Ansible module should be also successful.
