### ISSUE TITLE
unable to get windows 1709

### ISSUE THREAD

**Issue by sravs1993** [ptylenda/kubernetes-for-windows#2]
Hello,
I am struggling to create a kubernetes hybrid cluster on windows server 2016 data center edition in AWS. Can you please help me with more elaborated steps of how to create the 1709 VM and then deploy kubernetes? Immediate response would be appreciated. Thanks.

**Comment by pablodav** [comment]
Hi @sravs1993 

I'm trying to do same thing, last weekend I have been working on another project from @ptylenda and forked it to: https://github.com/pablodav/kubernetes-for-windows/tree/feature/testing-win1709

Just didn't create pull request here yet because I haven't finished the deployment as I had to work on some other things last days.

**Comment by sravs1993** [comment]
Thanks @pablodav can you just help me with some documentation as how you could do it?

**Comment by pablodav** [comment]
Hi @sravs1993 

Sorry to respond late, but I was working on some other priorities at work.

What other documentation do you need? I think the readme is quiet well explained https://github.com/pablodav/kubernetes-for-windows#ansible-usage 

I'm just trying it and will try to improve/fix anything once I have some findings and results.

**Comment by pablodav** [comment]
Hi @sravs1993 , I have just created the first pull request with my changes #5 , it has big modifications and new instructions in the Readme.

Probably this could help you: 

https://github.com/pablodav/kubernetes-for-windows#ansible-usage

**Comment by pablodav** [comment]
Hi @sravs1993 

I have something ready for a quickstart here: 

https://github.com/pablodav/kubernetes-for-windows-quickstart

More comments here:
https://github.com/kubernetes-incubator/kubespray/issues/2889

could you test it?

Note, all this was updated to windows 1803.

**Comment by pablodav** [comment]
I think it is ready to be closed
