### ISSUE TITLE
Joining test windows host for development

### ISSUE THREAD

**Issue by cpkuo** [ptylenda/kubernetes-for-windows#3]
Hello, I don't know where else to put this. Would you be available to help me setup a similar env using your scripts? I will compensate you of course. I have a Windows 10 machine running 1 Kube master VM and 1 Windows Core 1709 VM that I want to join as a node.

**Comment by pablodav** [comment]
@cpkuo probably you could try with my fork that has many fixes and changes

**Comment by pablodav** [comment]
Hi @cpkuo 
I have something ready for a quickstart here: 

https://github.com/pablodav/kubernetes-for-windows-quickstart

More comments here:
https://github.com/kubernetes-incubator/kubespray/issues/2889

could you test it?

**Comment by pablodav** [comment]
Note, all this was updated to windows 1803.

**Comment by pablodav** [comment]
I think it is ready to be closed with all last changed done.
